name: Automate Helm Chart Updates
on:
  workflow_dispatch:
    inputs:
      account:
        description: "Account name (stage or prod)"
        required: true
      repo:
        description: "Repository name"
        required: true

jobs:
  update-helm:
    runs-on: self-hosted-k8s
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Helm Chart
        run: ./scripts/update-helm.sh ${{ github.event.inputs.account }} ${{ github.event.inputs.repo }}